#########################################
### System-Api configuration          ###
#########################################
metricsConfig:
  monitor:
    interval: 45
    unit: SECONDS
  history:
    interval: 30
    unit: SECONDS
    purging:
      olderThan: 3
      unit: DAYS
      purgeEvery: 1
      purgeEveryUnit: DAYS
  cache:
    duration: 5
    unit: SECONDS
user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: true
graphQLPlayGround:
  enabled: true
#forwardHttps: false

#########################################
### Dropwizard specific configuration ###
#########################################
graphql:
  enableTracing: false
  queryCache: maximumSize=10000
  schemaFiles:
    - schema.graphqls

server:
  type: simple
  maxThreads: 100
  minThreads: 1
  maxQueuedRequests: 100
  idleThreadTimeout: 1 minute
  rootPath: /api/
  adminContextPath: /admin
  applicationContextPath: /
  connector:
      type: http
      port: 8080

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    "com.krillsson.sysapi":
      additive: false
      level: DEBUG
      appenders:
        - type: console