#########################################
### System-Api configuration          ###
#########################################
metricsConfig:
  monitor:
    interval: 45
    unit: SECONDS
  history:
    interval: 30
    unit: MINUTES
    purging:
      olderThan: 14
      unit: DAYS
      purgeEvery: 1
      purgeEveryUnit: DAYS
  cache:
    enabled: true
    duration: 5
    unit: SECONDS
user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: true
# web interface for running queries
graphQLPlayGround:
  enabled: true
# docker management and metrics support
docker:
  enabled: true
# resolve external IP and monitor internet connectivity
connectivityCheck:
  enabled: true
  address: https://ifconfig.me
# advertise service in local network for easier client setup
mDNS:
  enabled: true
forwardHttpToHttps: false
selfSignedCertificates:
  enabled: true
  ## automatically put external IP in CN
  populateCN: true
  ## automatically put internal IPs in SAN
  populateSAN: true
  ## manually populate CN and SAN below
  # commonName: sys-api.org
  # subjectAlternativeNames: [192.168.0.24, 10.8.0.24]

#########################################
### Dropwizard specific configuration ###
#########################################
graphql:
  enableTracing: false
  queryCache: maximumSize=10000
  schemaFiles:
    - schema.graphqls

server:
  maxThreads: 100
  minThreads: 1
  maxQueuedRequests: 100
  idleThreadTimeout: 1 minute
  rootPath: /api/
  adminContextPath: /admin
  applicationContextPath: /
  requestLog:
    appenders: [ ]
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: data/keystorewww.jks
      keyStorePassword: sys-api
      certAlias: sys-api-key
      validateCerts: false
      validatePeers: false
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ERROR

  # Logger-specific levels.
  loggers:
    "com.krillsson.sysapi":
      additive: false
      level: INFO
      appenders:
        - type: console
    "io.dropwizard":
      additive: false
      level: ERROR
      appenders:
        - type: console
    "io.dropwizard.server.ServerFactory":
      additive: false
      level: INFO
      appenders:
        - type: console
    "org.hibernate.SQL":
      additive: false
      level: ERROR
      appenders:
        - type: console
    "org.hibernate.type":
      additive: false
      level: ERROR
      appenders:
        - type: console
    "org.hibernate.stat":
      additive: false
      level: ERROR
      appenders:
        - type: console
    "org.hibernate.engine":
      additive: false
      level: ERROR
      appenders:
        - type: console
    "graphql.kickstart":
      additive: false
      level: ERROR
      appenders:
        - type: console